student_model_cfgs:
  - model_type: huggingface
    model_cfg:
      path: meta-llama/Meta-Llama-3-8B-Instruct
      name: llama-3-70b
    sample_cfg:
      num_return_sequences: 1

# can be overrided by per-model sample_cfg
general_student_sample_cfg:
  batch_size: 1
  num_return_sequences: 1
  do_sample: false
  temperature: 0.0
  eos_token_id: [128001, 128009]
  pad_token_id: 128001

exam_maker_type: code_metainfo
exam_maker_cfg:
  num_exam_questions: 300

exam_prompter_type: basic
exam_prompter_cfg:
  demo_template: "[[Question]]:\nHere is an example question, please understand it very carefully:\n{question}\nFirst, let's think step by step to find a complete problem-solving strategy. Then, write a python code based on the problem-solving strategy.\n\n[[RATIONALE]]:\n{rationale}\n\n[[Final Code]]:\n${answer}$\n"
  exam_template: "{demo}\n\n[[Question]]:\nPlease first understand the problem-solving approach in rationale of the aforementioned example, and then follow the example to solve the following similar type of problem:\n{question}\nFirst, let's think step by step to find a complete problem-solving strategy. Then, write a python code based on the problem-solving strategy.\n\n[[RATIONALE]]:\n"
  use_multi_round_conv: false

exam_scorer_type: code

teaching_plans: every